### ISSUE TITLE
git sync throws an error saying you do not have sufficient credentials even though i have credentials

### ISSUE THREAD

**Issue by rajofchennai** [kennethreitz/legit#101] opened 2013-03-14 12:30 UTC
Hi,

I have an issue with git sync which throws an exception with the below trace

`git sync` 
Pulling commits from the server.
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 45, in main
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 158, in cmd_sync
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.cli", line 80, in status_log
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.scm", line 117, in smart_pull
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/legit.scm", line 106, in fetch
  File "legit_r/build/pyi.darwin/legit_r/outPYZ1.pyz/git.cmd", line 377, in execute
git.exc.GitCommandError: 'git fetch origin' returned exit status 128: ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

But `git push origin master` works perfectly fine(so i think there should not be any permission issues)

My .git/config file looks like this

[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = false
[remote "origin"]
    fetch = +refs/heads/_:refs/remotes/origin/_
    url = git@github.com:[user]/[repo].git

I am not sure if it is a configuration issue or something else.

Rajesh

**Comment by weakish** [comment] 2017-07-19 10:20
Close it for now since it cannot be reproduced with recent versions of legit.

**Closed by weakish** 2017-07-19 10:20 UTC
