### ISSUE TITLE
TypeError: PackingType of packed-Refs not understood

### ISSUE THREAD

**Issue by samuelcole** [kennethreitz/legit#225] opened 2017-11-03 18:25 UTC
legit broke with `git version 2.15.0`

```
$ git sync
Traceback (most recent call last):
  File "/usr/local/bin/legit", line 11, in <module>
    load_entry_point('legit==0.4.1', 'console_scripts', 'legit')()
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/legit/cli.py", line 48, in main
    command.__call__(args)
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/legit/cli.py", line 502, in __call__
    return self.fn(*args, **kw_args)
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/legit/cli.py", line 204, in cmd_sync
    if branch in get_branch_names(local=False):
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/legit/scm.py", line 290, in get_branch_names
    branches = get_branches(local=local, remote_branches=remote_branches)
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/legit/scm.py", line 265, in get_branches
    for b in remote.refs:
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/git/remote.py", line 527, in refs
    out_refs.extend(RemoteReference.list_items(self.repo, remote=self.name))
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/git/util.py", line 932, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/git/refs/symbolic.py", line 592, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/usr/local/Cellar/legit/0.4.1/libexec/lib/python2.7/site-packages/git/refs/symbolic.py", line 92, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

**Comment by weakish** [comment] 2017-11-09 12:52
Cannot reproduce this on my machine.
Have you tried the 2.15.0 version released on Nov. 8?
Can you specify your  legit and  os version?

My setup:

- git 2.15.0
- legit both v0.4.1 (installed with `pip install legit`) and 325dd22fd0ed278
- osx 10.12.6

**Comment by samuelcole** [comment] 2017-11-09 21:22
Is it not this? https://github.com/gitpython-developers/GitPython/pull/689

I assumed you would just need to wait for a new `GitPython` release, and update the dependency.

**Comment by AnilRedshift** [comment] 2017-11-14 01:08
I can confirm that manually applying the patch that @samuelcole mentioned above fixes the issue.
Git 2.15.0
legit v0.4.1 (via brew install)

**Comment by reneruiz** [comment] 2017-11-14 20:51
Does this require a legit update or do I need to do something locally to fix it?

**Comment by Tatsh** [comment] 2017-11-16 07:30
Until the update comes you can do `https://github.com/gitpython-developers/GitPython/archive/master.zip`. I was affected by this with https://github.com/msiemens/PyGitUp .

**Comment by weakish** [comment] 2017-11-17 02:22
@reneruiz You can just update PyGitUp to `master` at now. After a new release of PyGitUp coming out, I will update the dependency list of legit.

**Comment by kennethreitz** [comment] 2017-11-25 16:15
I was just hit by this. I'll try to get a release out the door.

**Comment by kennethreitz** [comment] 2017-11-25 16:18
Oh, I see what's going on now. 

I confirm that the patch mentioned above fixes the issue.

**Comment by miketheman** [comment] 2017-12-22 15:10
It appears PyGitUp has released newer versions: https://github.com/msiemens/PyGitUp/releases

**Comment by miketheman** [comment] 2017-12-22 15:12
This appears to be fixed in the GitPython 2.1.8 version, as discussed here: https://github.com/gitpython-developers/GitPython/issues/687

**Closed** 2017-12-24 16:06 UTC
Labels: Bug

**Comment by reneruiz** [comment] 2018-02-06 18:50
Legit still doesn't work for me. It seems some of you have updated the GitPython dependency locally, but I have no idea how to do that. Any chance of a new release to fix this?

**Comment by weakish** [comment] 2018-02-07 14:50
@reneruiz Have you tried installing legit from github repository (the `develop` branch)?

**Comment by reneruiz** [comment] 2018-02-07 18:04
Unfortunately not, I installed legit through brew.  Could you provide instructions on how to install from the develop branch?

**Comment by weakish** [comment] 2018-02-08 12:25
@reneruiz Just updated README, added instructions. See 246ec45f74741
